[[redirects]]
	from = "/about"
	to = "/"
	status = 302

[[redirects]]
	from = "/slack"
	to = "https://ducompsoc.slack.com"
	status = 302

[[redirects]]
	from = "/constitution"
	to = "https://community.dur.ac.uk/computing.society/constitution.pdf"
	status = 302
	
[[redirects]]
	from = "/egm"
	to = "https://community.dur.ac.uk/computing.society/egm.pdf"
	status = 302

[[redirects]]
	from = "/scottlogic"
	to = "https://ducompsoc.typeform.com/to/H9pkxg5V"
	status = 302

[dev]
	publish = "build/"
