[[redirects]]
	from = "/about"
	to = "/"
	status = 302

[[redirects]]
	from = "/join"
	to = "http://eepurl.com/dKcvFQ"
	status = 302

[[redirects]]
	from = "/fb"
	to = "https://www.facebook.com/DurhamCompSoc"
	status = 302

[[redirects]]
	from = "/discord"
	to = "https://discord.gg/QDtMw5a2Ck"
	status = 302

[[redirects]]
	from = "/ins"
	to = "https://www.instagram.com/ducompsoc/"
	status = 302

[[redirects]]
	from = "/linkedin"
	to = "https://www.linkedin.com/company/ducompsoc/"
	status = 302

[[redirects]]
	from = "/sponsorshipdeck"
	to = "https://drive.google.com/file/d/1NdSjyCv39hsFdOKcOkDXjyuYhInRmObn/view?usp=sharing"
	status = 302

[dev]
	publish = "dist/"

[[plugins]]
	package = "netlify-plugin-chromium"