[[redirects]]
	from = "/about"
	to = "/"
	status = 302

[[redirects]]
	from = "/join"
	to = "https://docs.google.com/forms/d/e/1FAIpQLScjPyHlUbTRkK1rZa8mquWa7i8kLwWJErsMIQ80ml21jY73-A/viewform"
	status = 302

[[redirects]]
	from = "/fb"
	to = "https://www.facebook.com/DurhamCompSoc"
	status = 302

[[redirects]]
	from = "/discord"
	to = "https://discord.gg/2PKP2WuU2h"
	status = 302

[[redirects]]
	from = "/ins"
	to = "https://www.instagram.com/ducompsoc/"
	status = 302

[[redirects]]
	from = "/linkedin"
	to = "https://www.linkedin.com/company/ducompsoc/"
	status = 302

[[redirects]]
	from = "/sponsorshipdeck"
	to = "https://drive.google.com/file/d/1NdSjyCv39hsFdOKcOkDXjyuYhInRmObn/view?usp=sharing"
	status = 302

[[redirects]]
	from = "/nwg"
	to = "https://drive.google.com/drive/folders/1KWkUfCxbWgsu8PAnPCfzoq4TwgCjXLUO?usp=share_link"
	status = 302

[[redirects]]
	from = "/qrt"
	to = "https://www.qube-rt.com/careers/"
	status = 302

[[redirects]]
	from = "/qrt-tracks"
	to = "https://durhamuniversity-my.sharepoint.com/:b:/g/personal/jgcw74_durham_ac_uk/Ea7o7fwdGeRMhzhpD5loae0B31gukeH_yQXbLK5ofOZQRQ?e=ByBcUf"
	status = 302

[[redirects]]
	from = "/gdsc"
	to = "https://drive.google.com/file/d/1mNmLYH3xW0QEe78oRgcZHi-Capg2LtKw/view?usp=sharing"
	status = 302



[dev]
	publish = "build/"
